INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5083577677, 'dubravko pejakovski', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1078639433, 'Чих-Пых', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1212956264, 'Creepmxnine💦', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (420636628, 'Kim Chin [OOM]', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5402322032, 'дима дима', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5273265789, 'enemy', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (385077955, 'Danya M', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5474872671, 'нет хз', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (391414717, 'Руслан', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (923845043, 'Ксения', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5342680978, 'Дашулька 2', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5565968720, 'Мерри Попинс', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (925137273, '꧁⚣︎ 𝙰𝙻𝙴𝚇𝚄𝚂⚣︎꧂', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1310038124, 'Saleh Izzi', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (928716265, 'Лёша', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1429733567, 'Dima', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1305256830, 'Просто Макс', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (999380667, 'Sec Bary', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (127567241, 'Август', 'Авгу́ст', 5281481505, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5281481505, 'Коэффициент Абсорбции', 'Авгу́ст', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5485481415, 'Alan T. Navarro', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1662856311, '~☆Samurai☆~', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1802173129, 'Максим Малых', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (377884346, 'Женя Барбоскин', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (503041408, 'Lifeisbeautiful', 'Dirty Monk', 0, true);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1833747693, 'AMIR 13', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1087968824, 'Group', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (2031453140, 'アレクセイ ベスノフ', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1601759203, 'Секс на пляже', 'Авгу́ст', 5281481505, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (474779559, 'Lestrange RR', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (433803608, 'Светлана', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (622406983, '༄Alina࿐', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (772770751, '⚠️', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (900105364, 'Tomatckii Ivan', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (364532881, 'bla bla', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (597807757, 'Alina', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (189216114, 'фила', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (46701101, 'Lera', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (2108127122, 'Артём', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (961544581, 'кирюхин андрей', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (798245138, 'Emma Werner', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (823691428, 'Sergie K', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1014241184, 'Pupkin Pavel', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (424050585, 'Антикиллер', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5574150819, 'Drain Girl', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (931456433, 'Карина', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1127751437, '🆔яРина', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1606700742, 'кристина коновченко', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5305998157, 'Твой Сладкий', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1091573057, '', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1112913546, '', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (2122428522, 'Alina Kim', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (988059631, 'Никита Косов', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5543124779, 'Niki', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (50496196, 'Moon Moon', '', 1435023027, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5545366151, 'Белуга Машинист', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (2019625847, 'Тестировщик android прошивок', '', 1435023027, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1446890036, 'Рычаг Тумблера', 'Неокочевник Димасик', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5427388582, 'feyisa huluka', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1732619045, 'Saul Goodman', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (136817688, 'Channel', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1435023027, 'Moon Moon Jr', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (893189924, 'Ariman', '7 calamus 7', 0, true);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (800522859, 'Виталий Голосков', '', 0, true);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1624129420, 'решала Чечня', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (310082261, 'НАТАЛЬЯ', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (914816605, 'Lara', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (66854509, 'Islam Isaev', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5161364251, 'Хозяин Жизни', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1180177582, 'Диана 😝', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (430517846, 'Десерт', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (379876412, 'Denis', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (392112375, 'What is love', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5099239981, 'Alex Latt', 'Авгу́ст', 5281481505, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (2055905133, 'вергун с повидлом', 'Авгу́ст', 5281481505, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5242373095, 'Besa Prifti', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (513983086, 'lim lim', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (334910344, 'Supernatural Supernatural', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (371283507, 'Felix Zilich', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5121494535, 'Виталька Гладкокуст', '', 128697674, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1395642766, 'Flash Gordon', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5449877974, 'Jackson', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5217634701, 'Мяу', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1499888353, 'Deree Man', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (372492653, 'dimasick', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5025016693, 'Vasilisa Prepre….', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (2116930513, 'Малежик', '', 410302005, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5565335572, 'Гоша', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5480493750, 'mivaxa 😍', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (778332763, 'Лиза', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (809011520, 'Derpachi ', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5382363741, 'Київское метро', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1991533683, 'Makson Abramovich', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5596402478, 'Christine Hudson', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5038748126, 'Месье Фоломкин', 'Василий', 512485120, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (645792844, 'GAROU', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5125584001, 'Тимур Саркисов', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (856309866, 'Nikus', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1899518028, 'Limb6 Pxphn69', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5501539082, 'Ленок', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1174416403, 'Маришка', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1349007594, 'Game developer', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (254486742, 'moscowhustlanull', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (410302005, 'Sipovicnull', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (279421514, 'Alexandernull', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (215338273, 'N.S.null', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (128697674, 'Dmitrynull', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (433177413, 'Mikhailnull', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (146072069, 'Андрейnull', 'Андрей', 0, true);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1306131426, 'Valentina', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (948381775, 'Gerard Valkyrie', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (132487240, 'RR RR', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (475190537, 'Екатерина', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (988222779, 'Глеб Денисенко', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (554718592, 'Михаил Елисеев', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5650165358, 'Zed', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1090329641, 'QWERTY', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5226834142, 'Willian', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (420207590, 'бейч урок', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (644159185, 'Aleksandra Sonina', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (595959372, 'Яна', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5005843536, 'Евгения', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (486429387, 'Наташа', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5652116377, 'Lucienne', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5761057927, 'Валерия К', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1667903082, 'Киря', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1555202697, 'Жека', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (533648363, 'Андрей', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (910938784, 'Артём Сипатов', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1236969996, 'Вера 🐓', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5625474906, 'Сергей Скачков', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1445205786, 'ПОМИДОРКА ВКУСНАЯ :)', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1760264394, 'Pro Inostranec', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5586319103, 'Дим Димычь RTX', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5254056325, 'Christian Puliska', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1411742436, '@NikeTike', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (362689512, 'proIT', 'Александр Фоломкин', 0, true);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5487909542, 'IDETTE Pope', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5430842948, 'sp', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (2137244607, 'lil peep', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (427115542, 'FabFabk23', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (816397323, 'фила Простофиля', 'Андрей', 146072069, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5782360990, 'Настя.', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1540488195, 'лика.', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5606785663, 'А', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5262832329, 'محمد بن يوسف', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5059329468, 'Сергей', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5557565641, 'Дмитрий Крупенин', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5454744825, 'Александр', 'Василий', 512485120, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5941284757, 'Крутой Бизнесмен', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (1654172659, 'т', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (315641915, 'Bestia', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5427273375, 'Дима', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (5062639138, '+79685395639', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (2073577519, 'Молодой Человек', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (432675096, 'Истинный Нектарnull', '', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (512485120, 'Товарищnull', 'Василий', 0, false);
INSERT INTO public.folo_user (user_id, name, tag, main_id, anchor) VALUES (225028055, '2Thinknull', '', 0, false);